MOUSEKEY_ENABLE     	= yes
BOOTMAGIC_ENABLE    	= yes
COMBO_ENABLE		    = yes
SERIAL_DRIVER           = vendor
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
EXTRAKEY                = yes
